#!/bin/bash
brctl addbr bridge0
brctl addif bridge0 eth1
brctl addif bridge0 eth2

# Zero the IP address on the interfaces
ifconfig eth1 0.0.0.0
ifconfig eth2 0.0.0.0

# Start the bridge
ifconfig bridge0 up

